language: node_js
node_js:
- '10'
before_install:
- npm install -g typescript
- npm install -g tfx-cli
stages:
- build `
jobs:
  include:
  - stage: deploy
    if: branch = master
    script:
    - "(cd uglySqlScriptRunner && npm install && tsc)"
    - rm -rf uglySqlScriptRunner/node_modules
    - "(cd uglySqlScriptRunner && npm install --production)"
    - tfx extension create --manifest-globs vss-extension.json
deploy:
  provider: releases
  api_key:
    secure: "apWLgjq194zj5hIr8sBSFQx2GhjqAy3S+F761crM0N6kEDWPuq9o44/RL9HCyTqrhYLhGRzt7oD8eqxSB10umL9A8QsRQzJt52A/XK3g1iWAjNCXkTMulEihF3ege5DOFH4PZQGdsOfNIXNiReXEiR73bQx4gMIb/kq1hg527EhLr6sLXePr70+gQJsIREMjSrk4X4CQpB6A6gSUzHIt8wx4q2GgMUnA2MnqxGL7iqklYY9kEbDRHUcgDcDgB1DHEJd0xdgOm9cefZ2HFNoGgHpjL/x/0GnXEvW8a4AHGrTwOLvu4N8gJq9hReLplDyp1XAn7MjBfEjryiV1YF5yjz+hgg4Z9OfJL4iR65xVxStS0TKhjdb3dMs8/ALJ/3e4FdDzhGHY58ZM8mZ6GmgBPPWYUAmkHRSUZ4Esm9stfqUMgCSmUZDimn+HwNe8Kzd1GXagOJanrXsOjbJE4d3yEYqudJ/jzCOekS4c8Me22u+Z5/UZ3xh5i0VA4S0csA82CW9X9XHEhJ0DzLRUl4BdAG+vNP4qxeqZDjsYQEB+Jyi2Kg6sB8be37D1RaUYh5i7GTocxz7JbAq/2qfHv+ciQ2yUXP3KD8BXVQVEEmkedtcw5e6Yz+enhamJvLcsbTiiRwSZb4wx6Tw8eOGjjaLXox5O6rgrHhnttZcKuXIBj1A="
  file: "*.vsix"
  file_glob: true
  on:
    repo: adia-technology/ugly-sql-script-runner
  skip_cleanup: 'true'
