language: node_js
node_js:
- '10'
before_install:
- npm install -g typescript
- npm install -g tfx-cli
stages:
- build `
jobs:
  include:
  - stage: deploy
    if: branch = master
    script:
    - "(cd uglySqlScriptRunner && npm install && tsc)"
    - rm -rf uglySqlScriptRunner/node_modules
    - "(cd uglySqlScriptRunner && npm install --production)"
    - tfx extension create --manifest-globs vss-extension.json
    deploy:
      provider: releases
      api_key:
        secure: CyU3xICkEjnmG+E7+PYjeAWrIX28Ydx4+6nRa8Wf/Th06kBYhpoilr9YMLtvNd5ELsGKCHCL8gA39d+2re8dAIZU8AJWAARcF69IMAdWowRLbPaGpg0ahm9PTYglN9DdjGr4+D+AFR8RR32oK9tB9KvelwtdQv/M18iqKz02gEiO0tWFORyI244nAfGnVaNN2DLipd/uLXqaa3pelFUm6vWv9Vsxyv5sqYex5vGmS0dwRdPjW5RRqw6V7vbmKORu36cBXFo0f+o2gi6AsSGuw60RoALFTQLDzOWZGG1XlfiVAD8eTOH15Ye7K83SXsHKtefg7UHFe38nUDNEoCFztEztJ0Yfc8GrqCHRHEtdi73eTknSFjVL77c3v5cyiA3Sxvz1ctXXq2iGrY0IVak7bY5+hom7z50V8IizIUgVP2hAwjODMrOCnsMGPrZhKmFS9zgwRL/kcTS76f8HJ0CicJJQKbI+5grNWm6kvuXpGuR8FqkoYEHnS1MWgdi05/BrzVYCkfjg/IMr93YAJUMfX8nOjL151bcRZ/1TxiJD3sJHP9o6NeGJ6+SaDYsF+QFu81+ipsmDVqJYcLtlUPLPmJwGemL7JabGmjhlqC39sg317WszWc7tB4tMbPXzgy+s31pm26tPw/797zCwhDdCTIiWC2TIYr6r6sCqUnjQquw=
      file: "*.vsix"
      file_glob: true
      skip_cleanup: true
      on:
        repo: adia-technology/ugly-sql-script-runner

