language: node_js
node_js:
- '10'
before_install:
- npm install -g typescript
- npm install -g tfx-cli
stages:
- build `
jobs:
  include:
  - stage: deploy
    if: branch = master
    script:
    - "(cd uglySqlScriptRunner && npm install && tsc)"
    - rm -rf uglySqlScriptRunner/node_modules
    - "(cd uglySqlScriptRunner && npm install --production)"
    - tfx extension create --manifest-globs vss-extension.json
    deploy:
      provider: releases
      api_key:
        secure: XItvXpLneAlOxLTFi7rZTxWe4jWrOXAqYB9Bqx+eGPwfnA30KRfZLVp/LrE1zNdWUvYHfc1TW6e24S5HziprkEfD78X4iFHaj5qr74o3mAw3LwtgfhAa7A7cMjJa9DlpKkw/gbuorC6Uh1m05xf6jRkwxCfQcPh8XGSWoAZ4Y1Q6ErGzf8Gdnhz9p1prLKKD5KbOtnLQdYx44xGYbycF0+rV8RyFjBQSFGC44PqUaSlMCQvY2AJnY7cKdQKng65Bt9rcScjm4i1hAzWiazwohVmzA6ogQrjevIii1oPJwAdN3AjdYQ4bmq64/b0haHwiUXSeX1VXIUThP+jzgZIQv8/FbLUgATWHh2/GHHYJooIk9vNMwzWaQYUUtjA7RMwY9PiPlAqaPeeKTab6KKOyZiTaO+9wvTd7jmBt1aRss38VYbpU5BK1mGp0GkF11bKd7KBVJqNZ2CsI2kV0cuasOOaL29yFXpo/KDdMyQAyFEs9Xy3eEgusKwQzgx2a/xqr6SQRtFX8ly8Uoozcw9yHEvXRheoNAXtwxCu5c0U2Xxiga+hDpBJKOZFOYFlnRyu+s+is9FBL4QX4ur0J4M04hdLwttZP5091i6VYoI6msDjoyDExe+8oHYBf4yIp181+JfWTWKaSmQBuuuPqO7Id2qKNZKpk6fjNyKPtxamhxaI=
      file: "*.vsix"
      file_glob: true
      skip_cleanup: true
      on:
        repo: adia-technology/ugly-sql-script-runner

