language: node_js
node_js:
- '10'
before_install:
- npm install -g typescript
- npm install -g tfx-cli
stages:
- build `
jobs:
  include:
  - stage: deploy
    if: branch = master
    script:
    - "(cd uglySqlScriptRunner && npm install && tsc)"
    - rm -rf uglySqlScriptRunner/node_modules
    - "(cd uglySqlScriptRunner && npm install --production)"
    - tfx extension create --manifest-globs vss-extension.json
deploy:
  provider: releases
  api_key:
    secure: "AEseifb93IDuNmvC4WCciWiXaGPlwYo1cmZXh64KWlZxHdmKfVYYa0bhFha9li688aPyqhS1aXg8tKgYK97GzD52t/NYHOYbFdIQTrvAau8CZ6QgMoXpSe53OLUYPbC4pnwd3iUM9s3dAgH39/f2XPZUFocoN+5lkLwRLGu4EZVxQZcWuN3ytUzKCdea33Hr/NuAt9cDLCJ3SGgjQrg3hqmqg0iPjHzEulisHFeunWZJixG2Vn7Nio5joZ7OJK0T3YxBmeztPrHAfDBUwKF6yFGcUXeLcUtqEXKuL1tdz6ffciULI/zpxd/SB510SH1HfzvhFdCP/lQHqOwuA6rTa+u9PQ74MsQ/gDMWppn2C4CuIT+nv/39R88HltdTI7400wg92Or7Llc3tNh0NQdCdvyNgN/lJoAp3IVmilZE992bfMSS2AdVpAcJI4u3K1zeOs6j6KX+xZWt3/ECrRJ7EsjfD3+VWWJYuqrahMujouXgkG3BKRbhy3318RSC+TKKvqhV5nABQkiv6RLDBZGRSEL/PYDClol85Ao1h+5Lqn2T6cQ2Qu5IodaDnBUPt8OgYovNO9ml94kPJBFD2SWf5pWOuMY10Tfh9u5QqaHRgaAGOKdxUEWBg8vWYnEiJcb9YuwmgWTsbchsLNVoc/LPUmfvBRBSZ2e8rtLKKULkR1w="
  file: "*.vsix"
  file_glob: true
  on:
    repo: adia-technology/ugly-sql-script-runner
  skip_cleanup: 'true'
