language: node_js
node_js:
- '10'
before_install:
- npm install -g typescript
- npm install -g tfx-cli
stages:
- build `
jobs:
  include:
  - stage: deploy
    if: branch = master
    script:
    - "(cd uglySqlScriptRunner && npm install && tsc)"
    - rm -rf uglySqlScriptRunner/node_modules
    - "(cd uglySqlScriptRunner && npm install --production)"
    - tfx extension create --manifest-globs vss-extension.json
deploy:
  provider: releases
  api_key:
    secure: YiymAJLzdwXpDds1t37VmLs18SQk0sBzMwOWpsI7JPsKcMpaPoIJKcufuBUP6md1CcdHxHGNeBHf8E0scnj10oUrXDP6zk2zrLC1MeBK+C7qAYzROG7mDEZQeBC7D57X/9rZQbZ1rpzTHjtuBUnMyKhDYowLvGXYxncwTVqHCyyCCQRYmlOfozW4bsh2kw8EoFGueDTnACBTFZDcCCcDIxp5pJeUNU7Ouu7dLsGqSMM1WT986AODtMQI8RUjfbi4goN371mcI4F+iAlIzIyMi2Y1QJfQ0GVnhNG4feTGuUJi31nZ3eZEAph0TxCDlsUir7oJgdSGygBuuWOyjDIJ5LwyVRWsLORmh2QD4+7ZUgYFHTN+FBnWn/Hgnx6stXLM44O3ayNtnFYIoxzhcnbJVEOHpm4MTD5P6GndEOBxT5rK8iOcRc07VTJwAPDUFJa0t239ZFk3Mr5SX1lNp5ScFiZ90G/X/93CPdwsD1jry+oeUFnBP4fGdJSfXMzSd6BItpvjRnoJRfVsYZ/djDaQkkG4sQNezX0+1RVhvwl10n4c58j4sDglBKMGOsZDSjDkMQHiq/YXW7kPcUN1tRca3AQ+0bQcoEvwDAQ3/iZ7RDclxtyceEtEcVG8snX/z3PLbVWkn28R4yA8dvHWE4KYHwBelI5KtVwELBjmRExf8Xg=
  file: "*.vsix"
  file_glob: "*.vsix"
  on:
    repo: adia-technology/ugly-sql-script-runner
  skip_cleanup: 'true'
